window:
  height: 400
  width: 325
  font-scaling: 80
  background-color: "#A4FCD8"
file: "NuLAB_Logging_Output.csv"
mode: read
title: NuLAB Output v1.3
refresh_seconds: 1

tabs:
  - title: Messages and Latest Results
    key: 1
 
fields:
  - tab: 1
    header: Messages
    label: System Message
    type: textbox
    
  - tab: 1
    header: Voltage
    label: Power Supply Voltage
    type: textbox

  - tab: 1 
    header: N+N
    label: OBS Abs.
    type: textbox

  - tab: 1 
    label: Sample Conc.
    type: textbox

  - tab: 1 
    header: Nitrite
    label: OBS Abs.
    type: textbox

  - tab: 1 
    label: Sample Conc.
    type: textbox

  - tab: 1 
    header: Phosphate
    label: OBS Abs.
    type: textbox

  - tab: 1 
    label: Sample Conc.
    type: textbox

  - tab: 1 
    header: Ammonium
    label: OBS Abs.
    type: textbox

  - tab: 1 
    label: Sample Conc.
    type: textbox

